plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
    id 'me.modmuss50.mod-publish-plugin'
    id 'com.diffplug.spotless'
}

fabricApi {
    configureDataGeneration()
}

// ##################################################################################
// # Runs data gen using Fabric and moves generated resources to common.            #
// ##################################################################################
tasks.named('runDatagen') {
    doLast {
        def generatedDir = new File(project.projectDir, 'src/main/generated')
        def targetDir = new File(rootProject.projectDir, 'common/src/main/generated')

        println "Checking generatedDir: ${generatedDir.absolutePath}"

        if (generatedDir.exists()) {
            targetDir.mkdirs()

            // Copy files to the common module.
            ant.copy(todir: targetDir) {
                fileset(dir: generatedDir)
            }

            println "Copied generated data to: ${targetDir}"

            // Delete the original generated directory.
            if (generatedDir.deleteDir()) {
                println "Deleted original generated directory: ${generatedDir}"
            } else {
                println "Failed to delete: ${generatedDir} — possibly contains files still in use"
            }
        } else {
            println "No generated data found at: ${generatedDir}"
        }
    }
}
// END

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    modImplementation "mod.azure.azurelib:azurelib-fabric-${minecraft_version}:${azurelib_version}"
    modImplementation "curse.maven:spark-361579:5759670"
    //modImplementation "curse.maven:avp-1005026:7089601"  Will need updated once AVP updates for Azurelib fixes
    implementation("com.just:just-codec:0.1.0")
    implementation("com.just:just-core:0.1.0")
    modImplementation "maven.modrinth:fabric-permissions-api:0.3.3"
    modApi "com.terraformersmc:modmenu:${modmenu_version}"
}

loom {
    def aw = project(":common").file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            runDir("runs/client")
        }
        server {
            server()
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
            runDir("runs/server")
        }
    }
}

def keyPropsFile = new File(rootProject.projectDir, "key.properties")
if (keyPropsFile.exists()) {
    publishMods {
        def releaseProp = new Properties()
        releaseProp.load(new FileInputStream(keyPropsFile))
        file = remapJar.archiveFile
        changelog = rootProject.file("changelog.md").text
        type = STABLE
        modLoaders.add("fabric")

        curseforge {
            projectId = project.curseforgeID
            projectSlug = project.projectSlug
            accessToken = releaseProp.getProperty("curseKey")
            minecraftVersions.add("${minecraft_version}")
            requires {
                slug = "fabric-api"
            }
            requires {
                slug = "azurelib"
            }
            optional {
                slug = "modmenu"
            }
        }
        modrinth {
            projectId = project.modrinthID
            accessToken = releaseProp.getProperty('modrinthKey')
            minecraftVersions.add("${minecraft_version}")
            requires {
                slug = "fabric-api"
            }
            requires {
                slug = "azurelib"
            }
            optional {
                slug = "modmenu"
            }
        }
    }
}

tasks.withType(JavaExec) {
     enableAssertions = true
}
